# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
ENV['SUPPLY_METADATA_PATH'] = '../config/metadata/android'

platform :android do

    desc "Create APK/AAB files and generate screenshots"
    lane :prepare_for_deploy do
        gradle(
            print_command: false,
            task: 'clean cleanBuildCache assembleDebug assembleAndroidTest bundleRelease'
        )
        screengrab
        puts("\e[34mYour release apk has been generated and is located at: app/build/outputs/bundle/release/app.aab\e[0m")
        puts("\e[34mIf this is your first deployment; Please upload this file to the Google Play Console then run `fastlane deploy production:true/false`\e[0m")
        puts("\e[34mIf you have deployed this app before you can upload the new apk through the `fastlane deploy` command\e[0m")
    end

    desc 'Deploy a new version to the Google Play Store, deploys to beta environment by default, adding the production flag will allow production deployment'
    lane :deploy do |options|
        track = options[:production] ? 'production' : 'beta'
        upload_to_play_store(track: track)
    end

end
